general {
  ignore_dbus_inhibit = false
}

# Screenlock
listener {
  timeout = 600
  on-timeout = hyprlock # command to run when timeout has passed
  # on-resume = notify-send "Welcome back to your desktop!"
}

# Suspend/dpms
listener {
  timeout = 660

  # Laptop Settings
  on-timeout = systemctl suspend

  # Desktop Settings
  # on-timeout = hyprctl dispatch dpms off
  # on-resume = hyprctl dispatch dpms on
}
