windowrule = float,system_monitor
windowrule = size 1000 760,system_monitor
windowrule = move 454 192,system_monitor
windowrule = tile, ^(Brave-browser)$

windowrulev2 = float,title:(FloatingKitty)
windowrulev2 = move 50% 50%,title:(FloatingKitty)
windowrulev2 = size 400 300,title:(FloatingKitty)
