#!/bin/bash

if systemctl is-active --quiet docker; then
    echo '{"text": "󰡨", "tooltip": "Docker: Running", "class": "docker-active"}'
else
    echo '{"text": "󰡨", "tooltip": "Docker: Stopped", "class": "docker-inactive"}'
fi
